api/app/urls.py
import importlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

from users.views import password_reset_redirect

from . import views

urlpatterns = [
    url(r"^api/v1/", include("api.urls.deprecated", namespace="api-deprecated")),
    url(r"^api/v1/", include("api.urls.v1", namespace="api-v1")),
    url(r"^admin/", admin.site.urls),
    url(r"^health", include("health_check.urls", namespace="health")),
    url(r"^version", views.version_info),
    url(
        r"^sales-dashboard/",
        include("sales_dashboard.urls", namespace="sales_dashboard"),
    ),
    # this url is used to generate email content for the password reset workflow
    url(
        r"^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,"
        r"13}-[0-9A-Za-z]{1,20})/$",
        password_reset_redirect,
        name="password_reset_confirm",
    ),
    url(
        r"^config/project-overrides",
        views.project_overrides,
        name="project_overrides",
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r"^__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.SAML_INSTALLED:
    urlpatterns.append(path("api/v1/auth/saml/", include("saml.urls")))

if settings.WORKFLOWS_LOGIC_INSTALLED:
    module_path = settings.WORKFLOWS_LOGIC_MODULE_PATH
    workflow_views = importlib.import_module(f"{module_path}.views")
    urlpatterns.extend(
        [
            path("api/v1/features/workflows/", include(f"{module_path}.urls")),
            path(
                "api/v1/environments/<str:environment_api_key>/create-change-request/",
                workflow_views.create_change_request,
                name="create-change-request",
            ),
            path(
                "api/v1/environments/<str:environment_api_key>/list-change-requests/",
                workflow_views.list_change_requests,
                name="list-change-requests",
            ),
        ]
    )

if settings.SERVE_FE_ASSETS:
    # add route to serve FE assets for any unrecognised paths
    urlpatterns.append(url(r"^.*$", views.index, name="index"))

api/organisations/urls.py
from django.conf.urls import include, url
from rest_framework_nested import routers

from organisations.views import OrganisationWebhookViewSet
from users.views import FFAdminUserViewSet, UserPermissionGroupViewSet

from . import views
from .invites.views import InviteLinkViewSet, InviteViewSet
from .permissions.views import (
    UserOrganisationPermissionViewSet,
    UserPermissionGroupOrganisationPermissionViewSet,
)

router = routers.DefaultRouter()
router.register(r"", views.OrganisationViewSet, basename="organisation")

organisations_router = routers.NestedSimpleRouter(router, r"", lookup="organisation")
organisations_router.register(
    r"invites", InviteViewSet, basename="organisation-invites"
)
organisations_router.register(
    r"invite-links", InviteLinkViewSet, basename="organisation-invite-links"
)
organisations_router.register(
    r"users", FFAdminUserViewSet, basename="organisation-users"
)
organisations_router.register(
    r"groups", UserPermissionGroupViewSet, basename="organisation-groups"
)
organisations_router.register(
    r"webhooks", OrganisationWebhookViewSet, basename="organisation-webhooks"
)
organisations_router.register(
    "user-permissions",
    UserOrganisationPermissionViewSet,
    basename="organisation-user-permission",
)
organisations_router.register(
    "user-group-permissions",
    UserPermissionGroupOrganisationPermissionViewSet,
    basename="organisation-user-group-permission",
)

app_name = "organisations"

urlpatterns = [
    url(r"^", include(router.urls)),
    url(r"^", include(organisations_router.urls)),
]

api/sales_dashboard/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from . import views

app_name = "sales_dashboard"


urlpatterns = [
    path("", staff_member_required(views.OrganisationList.as_view()), name="index"),
    path(
        "organisations/<int:organisation_id>",
        views.organisation_info,
        name="organisation_info",
    ),
    path(
        "organisations/<int:organisation_id>/update_seats",
        views.update_seats,
        name="update_seats",
    ),
    path(
        "organisations/<int:project_id>/migrate_identities",
        views.migrate_identities_to_edge,
        name="migrate_identities",
    ),
    path(
        "organisations/<int:organisation_id>/update_max_api_calls",
        views.update_max_api_calls,
        name="update_max_api_calls",
    ),
    path(
        "email-usage/",
        staff_member_required(views.EmailUsage.as_view()),
        name="email-usage",
    ),
]

api/organisations/invites/models.py
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.db import models
from django.template.loader import get_template
from django.utils import timezone

from app.utils import create_hash
from organisations.models import Organisation, OrganisationRole
from users.models import FFAdminUser


class AbstractBaseInviteModel(models.Model):
    hash = models.CharField(max_length=100, default=create_hash, unique=True)
    date_created = models.DateTimeField("DateCreated", auto_now_add=True)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    role = models.CharField(
        choices=OrganisationRole.choices,
        max_length=50,
        default=OrganisationRole.USER,
    )

    class Meta:
        abstract = True


class InviteLink(AbstractBaseInviteModel):
    expires_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Datetime that the invite link will cease to be active. "
        "Leave blank to enable indefinitely.",
    )

    @property
    def is_expired(self):
        return self.expires_at is not None and timezone.now() > self.expires_at


class Invite(AbstractBaseInviteModel):
    email = models.EmailField()
    invited_by = models.ForeignKey(
        FFAdminUser, related_name="sent_invites", null=True, on_delete=models.CASCADE
    )
    frontend_base_url = models.CharField(max_length=500, null=False)

    class Meta:
        unique_together = ("email", "organisation")
        ordering = ["organisation", "date_created"]
        # reference existing table after moving to own app to avoid db inconsistencies
        db_table = "users_invite"

    def save(self, *args, **kwargs):
        # send email invite before saving invite
        self.send_invite_mail()
        super(Invite, self).save(*args, **kwargs)

    def get_invite_uri(self):
        return "%s%s" % (self.frontend_base_url, str(self.hash))

    def send_invite_mail(self):
        context = {
            "org_name": self.organisation.name,
            "invite_url": self.get_invite_uri(),
        }

        html_template = get_template("users/invite_to_org.html")
        plaintext_template = get_template("users/invite_to_org.txt")

        if self.invited_by:
            invited_by_name = self.invited_by.get_full_name()
            if not invited_by_name:
                invited_by_name = "A user"
            subject = settings.EMAIL_CONFIGURATION.get("INVITE_SUBJECT_WITH_NAME") % (
                invited_by_name,
                self.organisation.name,
            )
        else:
            subject = (
                settings.EMAIL_CONFIGURATION.get("INVITE_SUBJECT_WITHOUT_NAME")
                % self.organisation.name
            )

        to = self.email

        text_content = plaintext_template.render(context)
        html_content = html_template.render(context)
        msg = EmailMultiAlternatives(
            subject,
            text_content,
            settings.EMAIL_CONFIGURATION.get("INVITE_FROM_EMAIL"),
            [to],
        )
        msg.attach_alternative(html_content, "text/html")
        msg.send()

    def __str__(self):
        return "%s %s" % (self.email, self.organisation.name)

api/organisations/permissions/models.py
from __future__ import unicode_literals

from django.db import models

from organisations.managers import OrganisationPermissionManager
from organisations.models import Organisation
from permissions.models import AbstractBasePermissionModel, PermissionModel


class UserOrganisationPermission(AbstractBasePermissionModel):
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    user = models.ForeignKey("users.FFAdminUser", on_delete=models.CASCADE)


class UserPermissionGroupOrganisationPermission(AbstractBasePermissionModel):
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    group = models.ForeignKey("users.UserPermissionGroup", on_delete=models.CASCADE)


class OrganisationPermissionModel(PermissionModel):
    class Meta:
        proxy = True

    objects = OrganisationPermissionManager()

api/sales_dashboard/forms.py
import inspect
from datetime import date

from django import forms
from django.conf import settings
from django.core.mail import send_mail

from environments.models import Environment
from features.models import Feature
from organisations.models import Organisation
from projects.models import Project
from users.models import FFAdminUser


class MaxSeatsForm(forms.Form):
    max_seats = forms.IntegerField()

    def save(self, organisation, commit=True):
        organisation.subscription.max_seats = self.cleaned_data["max_seats"]
        organisation.subscription.save()


class MaxAPICallsForm(forms.Form):
    max_api_calls = forms.IntegerField()

    def save(self, organisation, commit=True):
        organisation.subscription.max_api_calls = self.cleaned_data["max_api_calls"]
        organisation.subscription.save()


class EmailUsageForm(forms.Form):
    email_address = forms.EmailField()

    def save(self, commit=True):
        message = inspect.cleandoc(
            f"""
            Current Flagsmith Stats on {date.today()}:

            Total Organisations = {Organisation.objects.all().count()}
            Total Projects = {Project.objects.all().count()}
            Total Environments = {Environment.objects.all().count()}
            Total Features = {Feature.objects.all().count()}
            Total Seats = {FFAdminUser.objects.all().count()}
            """
        )

        send_mail(
            subject="Flagsmith Usage Report",
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[self.cleaned_data["email_address"]],
            fail_silently=True,
        )

api/organisations/invites/views.py
from threading import Thread

from django.shortcuts import get_object_or_404
from rest_framework import status, viewsets
from rest_framework.decorators import action, api_view
from rest_framework.mixins import (
    CreateModelMixin,
    DestroyModelMixin,
    ListModelMixin,
    UpdateModelMixin,
)
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.throttling import ScopedRateThrottle
from rest_framework.viewsets import GenericViewSet

from organisations.invites.exceptions import InviteExpiredError
from organisations.invites.models import Invite, InviteLink
from organisations.invites.serializers import InviteLinkSerializer
from organisations.models import OrganisationRole
from organisations.permissions.permissions import (
    NestedOrganisationEntityPermission,
)
from organisations.serializers import OrganisationSerializerFull
from users.exceptions import InvalidInviteError
from users.models import FFAdminUser
from users.serializers import InviteListSerializer


@api_view(["POST"])
def join_organisation_from_email(request, hash):
    invite = get_object_or_404(Invite, hash=hash)

    try:
        request.user.join_organisation(invite)
    except InvalidInviteError as e:
        error_data = {"detail": str(e)}
        return Response(data=error_data, status=status.HTTP_400_BAD_REQUEST)

    if invite.organisation.over_plan_seats_limit():
        Thread(
            target=FFAdminUser.send_organisation_over_limit_alert,
            args=[invite.organisation],
        ).start()

    return Response(
        OrganisationSerializerFull(
            invite.organisation, context={"request": request}
        ).data,
        status=status.HTTP_200_OK,
    )


@api_view(["POST"])
def join_organisation_from_link(request, hash):
    invite = get_object_or_404(InviteLink, hash=hash)

    if invite.is_expired:
        raise InviteExpiredError()

    request.user.add_organisation(
        invite.organisation, role=OrganisationRole(invite.role)
    )

    if invite.organisation.over_plan_seats_limit():
        Thread(
            target=FFAdminUser.send_organisation_over_limit_alert,
            args=[invite.organisation],
        ).start()

    return Response(
        OrganisationSerializerFull(
            invite.organisation, context={"request": request}
        ).data,
        status=status.HTTP_200_OK,
    )


class InviteLinkViewSet(
    ListModelMixin,
    CreateModelMixin,
    UpdateModelMixin,
    DestroyModelMixin,
    GenericViewSet,
):
    serializer_class = InviteLinkSerializer
    permission_classes = (IsAuthenticated, NestedOrganisationEntityPermission)
    pagination_class = None

    def get_queryset(self):
        organisation_pk = self.kwargs.get("organisation_pk")
        user = self.request.user
        return InviteLink.objects.filter(
            organisation__in=user.organisations.all()
        ).filter(organisation__pk=organisation_pk)

    def perform_create(self, serializer):
        serializer.save(organisation_id=self.kwargs.get("organisation_pk"))

    def perform_update(self, serializer):
        serializer.save(organisation_id=self.kwargs.get("organisation_pk"))


class InviteViewSet(viewsets.ModelViewSet):
    serializer_class = InviteListSerializer
    permission_classes = (IsAuthenticated, NestedOrganisationEntityPermission)
    throttle_scope = "invite"

    def get_queryset(self):
        organisation_pk = self.kwargs.get("organisation_pk")
        user = self.request.user

        return Invite.objects.filter(organisation__in=user.organisations.all()).filter(
            organisation__id=organisation_pk
        )

    @action(detail=True, methods=["POST"], throttle_classes=[ScopedRateThrottle])
    def resend(self, request, organisation_pk, pk):
        invite = self.get_object()
        invite.send_invite_mail()
        return Response(status=status.HTTP_200_OK)

api/organisations/permissions/views.py
from __future__ import unicode_literals

from rest_framework import mixins, viewsets
from rest_framework.permissions import IsAuthenticated

from organisations.permissions.models import (
    UserOrganisationPermission,
    UserPermissionGroupOrganisationPermission,
)
from organisations.permissions.permissions import (
    NestedOrganisationEntityPermission,
)
from organisations.permissions.serializers import (
    UserOrganisationPermissionListSerializer,
    UserOrganisationPermissionUpdateCreateSerializer,
    UserPermissionGroupOrganisationPermissionListSerializer,
    UserPermissionGroupOrganisationPermissionUpdateCreateSerializer,
)


class BaseOrganisationPermissionViewSet(
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    mixins.DestroyModelMixin,
    mixins.UpdateModelMixin,
    viewsets.GenericViewSet,
):
    pagination_class = None
    permission_classes = [IsAuthenticated, NestedOrganisationEntityPermission]

    def perform_create(self, serializer):
        serializer.save(organisation_id=self.kwargs.get("organisation_pk"))


class UserOrganisationPermissionViewSet(BaseOrganisationPermissionViewSet):
    filterset_fields = ["user"]

    def get_queryset(self):
        return UserOrganisationPermission.objects.select_related("user").filter(
            organisation_id=self.kwargs.get("organisation_pk")
        )

    def get_serializer_class(self):
        return {"list": UserOrganisationPermissionListSerializer}.get(
            self.action, UserOrganisationPermissionUpdateCreateSerializer
        )


class UserPermissionGroupOrganisationPermissionViewSet(
    BaseOrganisationPermissionViewSet
):
    filterset_fields = ["group"]

    def get_queryset(self):
        return UserPermissionGroupOrganisationPermission.objects.select_related(
            "group"
        ).filter(organisation_id=self.kwargs.get("organisation_pk"))

    def get_serializer_class(self):
        return {"list": UserPermissionGroupOrganisationPermissionListSerializer}.get(
            self.action, UserPermissionGroupOrganisationPermissionUpdateCreateSerializer
        )

api/sales_dashboard/templates/sales_dashboard/base.html
{% load sales_dashboard_extras %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'sales_dashboard/css/bootstrap.min.css' %}"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
    <title>Flagsmith Sales Dashboard</title>
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Flagsmith</a>
      <form method="get" action="{% url 'sales_dashboard:index' %}" class="form-inline w-100">
        {% csrf_token %}
        <input class="form-control mr-sm-2 w-100=" type="search" placeholder="Search" aria-label="Search" name="search" value="{{ search }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'admin:logout' %}">Sign out</a>
    </li>
  </ul>
</nav>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

api/sales_dashboard/templates/sales_dashboard/email-usage.html
{% extends "sales_dashboard/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "sales_dashboard/nav.html" %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <form method="post" action="{% url 'sales_dashboard:email-usage' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit"/>
            </form>
        </main>
    </div>
</div>
{% endblock %}

api/sales_dashboard/templates/sales_dashboard/home.html
{% extends "sales_dashboard/base.html" %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    {% include "sales_dashboard/nav.html" %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Organisations</h1>
      </div>

      <div class="sort-form">
        <form action="{% url 'sales_dashboard:index' %}" method="get" class="form-inline float-right">
          <select name="filter_plan" id="filter-plan" class="custom-select m-1">
            <option value="" {% if not filter_plan %}selected{% endif %}>Filter Plan</option>
            <option value="free" {% if filter_plan == "free" %}selected{% endif %}>Free</option>
            <option value="start" {% if filter_plan == "start" %}selected{% endif %}>Start Up</option>
            <option value="scale" {% if filter_plan == "scale" %}selected{% endif %}>Scale Up</option>
          </select>
          <select name="sort_field" id="sort-field" class="custom-select m-1" value="{{ sort_field }}">
            <option value="" {% if not sort_field %}selected{% endif %}>Sort by...</option>
            <option value="num_users" {% if sort_field == "num_users" %}selected{% endif %}>Seats</option>
            <option value="num_projects" {% if sort_field == "num_projects" %}selected{% endif %}>Projects</option>
            <option value="num_features" {% if sort_field == "num_features" %}selected{% endif %}>Flags</option>
            <option value="num_segments" {% if sort_field == "num_segments" %}selected{% endif %}>Segments</option>
            <option value="num_24h_calls" {% if sort_field == "num_24h_calls" %}selected{% endif %}>24h API calls</option>
            <option value="num_7d_calls" {% if sort_field == "num_7d_calls" %}selected{% endif %}>7d API calls</option>
            <option value="num_30d_calls" {% if sort_field == "num_30d_calls" %}selected{% endif %}>30d API calls</option>
          </select>
          <select name="sort_direction" id="sort-direction" class="custom-select m-1">
            <option value="ASC" {% if not sort_direction or sort_direction == "ASC" %}selected{% endif %}>Ascending</option>
            <option value="DESC" {% if sort_direction == "DESC" %}selected{% endif %}>Descending</option>
          </select>
          <button type="submit" class="btn btn-primary m-1">Apply</button>
        </form>
      </div>

      <div class="table-responsive">
        <table class="table table-striped table-sm" data-toggle="table">
          <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Plan</th>
              <th>Users</th>
              <th>Seats</th>
              <th>Projects</th>
              <th>Flags</th>
              <th>Segments</th>
              <th>24h</th>
              <th>7d</th>
              <th>30d</th>
            </tr>
          </thead>
          <tbody>
            {% for org in object_list %}
            <tr class="{% if org.has_subscription and not org.is_paid %}table-danger{% elif org.over_plan_seats_limit %}table-warning{% endif %}">
              <td>{{org.id}}</td>
              <td><a href="/sales-dashboard/organisations/{{org.id}}">{{org.name}}</a></td>
              <td>
                {% if org.has_subscription %}
                {{org.subscription.plan}} - {{org.subscription.payment_method}}
                {% else %}
                Free
                {% endif %}
              </td>
              <td>{{org.num_users}}</td>
              <td>{{org.subscription.max_seats|default:1}}</td>
              <td>{{org.num_projects}}</td>
              <td>{{org.num_features}}</td>
              <td>{{org.num_segments}}</td>
              <td>{{org.num_24h_calls|intcomma}}</td>
              <td>{{org.num_7d_calls|intcomma}}</td>
              <td>{{org.num_30d_calls|intcomma}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?{% query_transform request page=1 %}">&laquo; first</a>
            <a href="?{% query_transform request page=page_obj.previous_page_number %}">previous</a>
            {% endif %}

            <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?{% query_transform request page=page_obj.next_page_number %}">next</a>
            <a href="?{% query_transform request page=page_obj.paginator.num_pages %}">last &raquo;</a>
            {% endif %}
          </span>
        </div>
      </div>
    </main>
  </div>

</div>
{% endblock %}

api/sales_dashboard/templates/sales_dashboard/organisation.html
{% extends "sales_dashboard/base.html" %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "sales_dashboard/nav.html" %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">
                    Organisation: <strong>{{organisation.name}}</strong> 
                    - Plan: <strong>{{ organisation.subscription.plan|default:"Free"}}</strong>
                    {% if organisation.has_subscription and not organisation.is_paid %}<span class="badge badge-danger">Subscription Cancelled</button>{% endif %}
                </h1>
            </div>

            {% if organisation.has_subscription %}
                <form method="POST" action="{% url 'sales_dashboard:update_seats' organisation.id %}">
                    {% csrf_token %}
                    {{max_seats_form}}
                    <input type="submit"/>
                </form>
                <form method="POST" action="{% url 'sales_dashboard:update_max_api_calls' organisation.id %}">
                    {% csrf_token %}
                    {{max_api_calls_form}}
                    <input type="submit"/>
                </form>
            {% else %}
                <h3>Seats: <strong>{{organisation.subscription.max_seats|default:0 }}</strong></h3>
            {% endif %}

            <h2>API Calls</h2>
            <table class="table table-striped table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th>24h</th>
                        <th>7d</th>
                        <th>30d</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{api_calls.24h|intcomma}}</td>
                        <td>{{api_calls.7d|intcomma}}</td>
                        <td>{{api_calls.30d|intcomma}}</td>
                        </tr>
                </tbody>
            </table>

            <h2>Projects</h2>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Created</th>
                            <th>Name</th>
                            <th>Environments</th>
                            <th>Features</th>
                            <th>Segments</th>
                            <th>Dynamo DB Enabled</th>
                            <th>Identity Count</th>
                            <th>Identity Migration Status</th>
                            <th>Migrate Identity</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for project in organisation.projects.all %}

                        <tr>
                            <td>{{project.id}}</td>
                            <td>{{project.created_date}}</td>
                            <td>{{project.name}}</td>
                            <td>{{project.environments.all.count}}</td>
                            <td>{{project.features.all.count}}</td>
                            <td>{{project.segments.all.count}}</td>
                            <td>{{project.enable_dynamo_db}}</td>
                            <td>{{identity_count_dict|get_item:project.id}}</td>
                            <td>{{identity_migration_status_dict|get_item:project.id}}</td>
                            <td>
                            <form method="POST" class="form-inline" action="{% url 'sales_dashboard:migrate_identities' project.id %}">
                                {% csrf_token %}
                                <input value="migrate identities" {% if identity_migration_status_dict|get_item:project.id != "MIGRATION_NOT_STARTED" %} {{'disabled'}} {% endif %} type="submit"/>
                            </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <h2>Seats in Use: <strong>{{ organisation.users.count }}</strong></h2>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email Address</th>
                            <th>Date Registered</th>
                            <th>Last Logged In</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in organisation.users.all %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.first_name}}</td>
                            <td><a href="mailto:{{user.email}}">{{user.email}}</a></td>
                            <td>{{ user.date_joined }}</td>
                            <td>{{ user.last_login }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
                <div class="container">
                    <canvas id="examChart"></canvas>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
var ctx = document.getElementById("examChart").getContext("2d");
var myChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: {{labels}},
    datasets: [
      {
        label: 'Flags',
        data: {{flags}},
        backgroundColor: '#D6E9C6',
      },
      {
        label: 'Identities',
        data: {{identities}},
        backgroundColor: '#FAEBCC',
      },
      {
        label: 'Traits',
        data: {{traits}},
        backgroundColor: '#EBCCD1',
      }
    ]
  },
  options: {
    scales: {
      xAxes: [{ stacked: true }],
      yAxes: [{ stacked: true }]
    }
  }
});
</script>
{% endblock %}